In [5]:
#Pandas (створити dataframe різними способами, провести маніпуляції з даними (head, describe, iloc, loc ...))

import pandas as pd

#Create
df = pd.DataFrame({
     'Film': ['DC studio', 'Dune', 'James Bond', 'Marvel','American History'],
     'Rating': [6.0, 5.8, 7.7, 8.1, 4.9],
     'Budget': [1.4, 2.2, 3, 11, 0.8]
}, index=['DC', 'Du', 'JB', 'MaR','AH'])
df.index.name = 'Filt studio code'
print("\nThe data frame is\n",df)
#Head
print("\nHead of 2\n",df.head(2))
#Describe
print("\nDescribe\n",df.describe())
#loc
print("\nLoc from 'Du' to 'AH' is\n",df.loc['Du':'AH', :])
#Iloc
print("\nLoc of '3' is\n",df.iloc[0])
#Sort
print("\nSort by Rating > 6.5\n",df[df.Rating > 6.5][['Film', 'Budget']])
#Add Series
df['Top Actor'] = [4, 5, 4, 20, 2]
print("\nAdd one series\n",df)
#Drop

#df.drop(['Top Actor'], axis='columns') Не работает почему то =(
#print("\nDrop one series\n",df)
del df['Top Actor']
print("\nDrop one series\n",df)

The data frame is
                               Film  Rating  Budget
Filt studio code
DC                       DC studio     6.0     1.4
Du                            Dune     5.8     2.2
JB                      James Bond     7.7     3.0
MaR                         Marvel     8.1    11.0
AH                American History     4.9     0.8

Head of 2
                        Film  Rating  Budget
Filt studio code
DC                DC studio     6.0     1.4
Du                     Dune     5.8     2.2

Describe
          Rating     Budget
count  5.000000   5.000000
mean   6.500000   3.680000
std    1.350926   4.175165
min    4.900000   0.800000
25%    5.800000   1.400000
50%    6.000000   2.200000
75%    7.700000   3.000000
max    8.100000  11.000000

Loc from 'Du' to 'AH' is
                               Film  Rating  Budget
Filt studio code
Du                            Dune     5.8     2.2
JB                      James Bond     7.7     3.0
MaR                         Marvel     8.1    11.0
AH                American History     4.9     0.8

Loc of '3' is
 Film      DC studio
Rating            6
Budget          1.4
Name: DC, dtype: object

Sort by Rating > 6.5
                         Film  Budget
Filt studio code
JB                James Bond     3.0
MaR                   Marvel    11.0

Add one series
                               Film  Rating  Budget  Top Actor
Filt studio code
DC                       DC studio     6.0     1.4          4
Du                            Dune     5.8     2.2          5
JB                      James Bond     7.7     3.0          4
MaR                         Marvel     8.1    11.0         20
AH                American History     4.9     0.8          2

Drop one series
                               Film  Rating  Budget  Top Actor
Filt studio code
DC                       DC studio     6.0     1.4          4
Du                            Dune     5.8     2.2          5
JB                      James Bond     7.7     3.0          4
MaR                         Marvel     8.1    11.0         20
AH                American History     4.9     0.8          2

Drop one series
                               Film  Rating  Budget
Filt studio code
DC                       DC studio     6.0     1.4
Du                            Dune     5.8     2.2
JB                      James Bond     7.7     3.0
MaR                         Marvel     8.1    11.0
AH                American History     4.9     0.8